### ISSUE TITLE
SILENT INSTALL SUGGESTION

### ISSUE THREAD

**Issue by bcurran3** [dittodhole/chocolatey-dashlane#1]
You might want to consider adding the following after `Install-ChocolateyPackage (blah blah)`:

```
Start-Sleep -s 20
if((get-process "Dashlane" -ea SilentlyContinue) -eq $Null){ 
    Write-Host "Dashlane NOT running." 
  }else{ 
    Write-Host "Stopping Dashlane process..."
    Stop-Process -processname "Dashlane"
  }

if((get-process "DashlanePlugin" -ea SilentlyContinue) -eq $Null){ 
    Write-Host "DashlanePlugin currently NOT running." 
  }else{ 
    Write-Host "Stopping DashlanePlugin process..."
    Stop-Process -processname "DashlanePlugin"
  }
```

to the install so that it will be silent since Dashlane runs after install.

I do this in a lot of my packages. Some moderators don't like it, some don't care. I think it's a cleaner install as the user can run the program when he/she wants to instead of it being forced on them during install.

**Comment by dittodhole** [comment]
Thanks for bringing this to my attention - I must admit, I am by no means a Chocolatey expert, so I am very thankful for any suggestions regarding my packages.

I will have  a look at this issue - but don't expect any instant or rapid progress, as I am currently very busy, and have other things in my pipeline ...
If you want to participate, you can fork my package, include your enhancements, and send me a PR.


Best
Andreas

**Comment by dittodhole** [comment]
Had some time, and implemented a "kill of process after installation" with 
a17721d.

Thanks for your suggestion - will be released with the next version.


Best
Andreas
